CosmosOperationCanceledException: Fix handler to catch all operation cancelled exceptions (#1666)
* Updated operation cancelled exception handling

* Added tests to verify the new exception is used.